"""Derive catalogue documentation and diagram data from the runtime JSON source."""

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CATALOGUE = "robotops/robotics/catalogue-v1.json"
DOCUMENT = "docs/generated/product-tool-catalogue.md"
MERMAID = "publication/generated/product-tool-compatibility.mmd"


def catalogue_data(root: Path = ROOT) -> dict[str, Any]:
    data: dict[str, Any] = json.loads((root / CATALOGUE).read_text(encoding="utf-8"))
    return data


def compatibility_rows(data: dict[str, Any]) -> tuple[list[str], list[list[str]]]:
    tools = [tool["tool_id"] for tool in data["tools"]]
    rows = [
        [product["sku"] + " / " + product["family"].replace("_", " ")]
        + [product["compatibility"][tool] for tool in tools]
        for product in data["products"]
    ]
    return ["Product", *tools], rows


def compatibility_mermaid(data: dict[str, Any]) -> str:
    headers, rows = compatibility_rows(data)
    lines = ["flowchart TB", '  H["' + " | ".join(headers) + '"]']
    previous = "H"
    for index, row in enumerate(rows, 1):
        ident = f"P{index}"
        lines.extend(["  " + ident + '["' + " | ".join(row) + '"]', f"  {previous} --> {ident}"])
        previous = ident
    return "\n".join(lines) + "\n"


def document(data: dict[str, Any]) -> str:
    headers, rows = compatibility_rows(data)
    lines = [
        "# Synthetic product and tool catalogue",
        "",
        "Generated by `python -m tools.generate_robotics_docs` from "
        "[the runtime catalogue](../../robotops/robotics/catalogue-v1.json). "
        "Change that source and regenerate; do not maintain a separate compatibility matrix.",
        "",
        "Classification: **SIMULATOR_DESIGN**. These fixtures and constraints are not "
        "manufacturer gripper specifications or customer product data. Catalogue availability "
        "does not by itself prove integrated scenario acceptance.",
        "",
        f"Profile `{data['profile_version']}`; product catalogue "
        f"`{data['product_catalog_version']}`; tool catalogue `{data['tool_catalog_version']}`; "
        f"schema `{data['schema_version']}`.",
        "",
        "## Product fixtures",
        "",
        "| SKU / family | Dimensions (m) | Mass range (kg) | Preferred tool |",
        "|---|---|---|---|",
    ]
    for product in data["products"]:
        preferred = next(tool for tool, grade in product["compatibility"].items() if grade == "P")
        dimensions = " x ".join(f"{value:.3f}" for value in product["dimensions_m"])
        lines.append(
            f"| {product['sku']} / {product['family'].replace('_', ' ')} | {dimensions} | "
            f"{product['mass_min_kg']:.2f}-{product['mass_max_kg']:.2f} | {preferred} |"
        )
    lines += [
        "",
        "## Compatibility",
        "",
        "P = preferred; C = candidate-compatible; N = disallowed. Mass, geometry and "
        "availability filters still apply to P/C candidates; a C entry alone does not "
        "guarantee that a particular fixture can be picked by that tool.",
        "",
        "| " + " | ".join(headers) + " |",
        "|" + "---|" * len(headers),
        *("| " + " | ".join(row) + " |" for row in rows),
        "",
        "```mermaid",
        compatibility_mermaid(data).rstrip(),
        "```",
        "",
        "## Synthetic tool limits",
        "",
        "| Tool | Maximum simulated mass (kg) | Geometry rule | Collision envelope (m) |",
        "|---|---|---|---|",
    ]
    for tool in data["tools"]:
        rule = tool["constraints"]
        match rule["kind"]:
            case "flat_top":
                geometry = (
                    "Flat top >= "
                    + " x ".join(f"{v:.3f}" for v in rule["minimum_flat_top_m"])
                    + " m"
                )
            case "grasp_width" | "soft_envelope":
                geometry = (
                    rule["kind"].replace("_", " ") + ": "
                    f"{rule['minimum_width_m']:.3f}-{rule['maximum_width_m']:.3f} m"
                )
            case "under_clearance":
                geometry = "Synthetic under-clearance required"
            case other:
                raise ValueError(f"Unsupported geometry rule in documentation: {other}")
        envelope = " x ".join(f"{v:.3f}" for v in tool["collision_envelope_m"])
        lines.append(
            f"| {tool['tool_id']} / {tool['display_name']} | "
            f"{tool['max_simulated_mass_kg']:.2f} | {geometry} | {envelope} |"
        )
    workspace = data["workspace"]
    lines += [
        "",
        "## Operational envelope",
        "",
        f"The validator's synthetic envelope uses radius {workspace['radial_limit_m']:.2f} m, "
        f"TCP Z {workspace['min_z_m']:.2f}-{workspace['max_z_m']:.2f} m, and safe transfer "
        f"Z {workspace['safe_transfer_z_m']:.2f} m. Frame `{workspace['frame_id']}`, "
        f"calibration `{workspace['calibration_version']}`.",
        "",
        "Manufacturer public-reference metadata is separate and never replaces these "
        "simulator-owned validation limits. Motion timings are "
        "SIMULATOR_PRESENTATION_TIMING, not robot-performance measurements.",
        "",
    ]
    return "\n".join(lines)


def generate(root: Path = ROOT, *, check: bool = False) -> list[str]:
    data = catalogue_data(root)
    outputs = {DOCUMENT: document(data), MERMAID: compatibility_mermaid(data)}
    stale = []
    for name, content in outputs.items():
        path = root / name
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(name)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    return stale


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = generate(check=args.check)
    if args.check and stale:
        raise SystemExit("Stale generated robotics documentation: " + ", ".join(stale))
    print(
        "Catalogue documentation matches runtime source."
        if args.check
        else "Generated catalogue documentation."
    )


if __name__ == "__main__":
    main()
