from robotops.domain.models import Fault

OBSERVATION_FAULTS = {
    Fault.LOW_CONFIDENCE_OBSERVATION,
    Fault.CONTRADICTORY_OBSERVATION,
    Fault.STALE_OBSERVATION,
    Fault.MISSING_OBSERVATION,
    Fault.POSE_UNCERTAINTY,
}
RUNTIME_FAULTS = {
    Fault.DROP_ACK_AFTER_EFFECT,
    Fault.DROP_ACK_BEFORE_EFFECT,
    Fault.ROBOT_COMMAND_FAILURE,
    Fault.CELL_FAULT,
    Fault.LOGICAL_ESTOP,
}
